### ISSUE TITLE
NBT specific items

### ISSUE THREAD

**Issue by nuttyNaoko** [Jaimss/moducore#33]
could be done without changing the base command too much, 
`/give tag item_name{nbt:1,nbt:2}`

Other alternative is allowing the `minecraft:` prefix.
Which then uses the vanilla give command, which already has nbt stuff working, obviously.
`/give minecraft:item_name{nbt:1,nbt:2}`

This can then further be expanded if some plugins have custom namespaces like `coolnamespace:cool_item`

**Comment by Jaimss** [comment]
Thanks for the suggestion. The minecraft give command already supports this, and it wouldn't be a trivial feature to add. I realize ModuCore was overwriting minecraft's give command completely. [v0.4.1](https://github.com/Jaimss/moducore/releases/tag/0.4.1) fixes this. If you decide you have no use for ModuCore's give command, you can always disable it in the modules.yml.

If anyone would like to add this feature in the future, I will probably merge it, but I will not add it myself.
